### ISSUE TITLE
Which tag is used: global tag or submission tag? 

### ISSUE THREAD

**Issue by jumbosushi** [DataDog/dogstatsd-ruby#157]
I have a question on how Datadog handles duplicate tag keys. DogStatsD allows an instance to be instantiated with Global Tags, and also allows metric submissions to include tags.  In [`Datadog::Statsd::Serialization::TagSerializer#format`](https://github.com/datadog/dogstatsd-ruby/blob/51e0e194584a1b3f8f26542cf47a52c1b99a5200/lib/datadog/statsd/serialization/tag_serializer.rb#L18-L28), we see that DogStatsD concatenates submission tags with global tags

```ruby
tag_list =  if message_tags && message_tags.any?
              global_tags + to_tags_list(message_tags)
            else
              global_tags
            end
```

For example, what happens when there is a global tag `Foo:1` and the submission tag includes a tag called `Foo:2`? Is only one of the two used, or are they both used? Based on the implementation it looks like this library sends the following string to Datadog:
```
Foo:1,Foo2
```

We would like the submission tag to overwrite the global tag with the same tag key, but I'm not sure if that's possible based on the code.

**Comment by djmitche** [comment]
In general, tags are treated as a list of strings, rather than a key-value mapping.  So a metric with `foo:1,foo:2` would appear to have tags `foo:1` and `foo:2`.  At some points in the Datadog app that appears as two values for the `foo` key.

In a more realistic example, this might make more sense.  For example, if a postgres server is used for three apps, it might have tags `app:one`, `app:duo`, and `app:drie`.  Then a filter for any one of those apps would identify the postgres server's metrics.

To answer the final question, there's currently no way to *remove* a global tag for a particular submission.  My intuition is that any configuration supporting doing so would be more complex than just omitting global tags entirely and submitting the appropriate set of tags at each statistic call (count, gauge, etc.).
