### ISSUE TITLE
Test suite hanging since updating from 5.0.1 to 5.1

### ISSUE THREAD

**Issue by jeffblake** [DataDog/dogstatsd-ruby#198]
My test suite hangs now at some random test until I Control-C quit it, where I then get this stack trace:
 
<img width="1155" alt="Screen Shot 2021-07-09 at 7 13 43 AM" src="https://user-images.githubusercontent.com/620564/125091538-5a963e00-e085-11eb-9efa-f51c7828c4ed.png">

**Comment by remeh** [comment]
Hey @jeffblake thanks for having opened an issue!

I expect that next release of `dd-trace-rb` will solve your issue (it will be using the `single_thread` mode introduced in DogStatsD-ruby v5.2.0, because it exists some problems with application/tests using forks and recent releases of DogStatsD-ruby). I'll let you know here once it has been released.

Meanwhile, a solution would be to pin `dogstatsd-ruby` to version `4.8.3` in you project.
Please let me know if that doesn't work for you.

**Comment by djmitche** [comment]
We'll consider this solved.  We can re-open if not!
