### ISSUE TITLE
tag parsing issue

### ISSUE THREAD

**Issue by kwwalter** [DataDog/dogstatsd-ruby#31]
Hey, it looks like there's a slight issue with how this library parses tags. A user reached out to me and was using this library to submit a metric with a tag formatted like this: 

`:tags=>["input_file_format:v1,v2,v3,v4,v5,v6"]`

However, when this metric is submitted, it appears in the UI with the following tags: 

```
input_file_format:v1
v2
v3
v4
v5
v6
```

This tag should not be treated like a comma-separated list of tags, though, since the tag is contained in one set of quotes. Based on [how tags are handled](https://help.datadoghq.com/hc/en-us/articles/203764715-What-are-valid-tags-), these commas should be replaced with underscores, correct?

**Comment by degemer** [comment]
Hey @kwwalter, actually commas are used to separate tags when multiple tags are sent to Datadog.
For instance, a metric with tags `role:database` and `table:customers` will actually be sent as `role:database,table:customers` (you may already know that, just to be sure).
That's why this example doesn't work.

I don't think we can change this behavior since it's actually a reserved character. (I checked, datadogpy has the same behavior, and the agent too)

**Comment by degemer** [comment]
This is not allowed anymore with 2.0.0, `,` in tags are removed, see https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#tags
